version: '3.8'
services:
  app:
    build: .
    ports:
      - "8000:8000" # Mapea el puerto 8000 del contenedor al puerto 8000 de tu máquina
    environment:
      - DATABASE_URL=postgresql://postgres:1986@db:5432/inyectoras_db
      - SESSION_SECRET=secret1986
      - PORT=8000
    depends_on:
      - db # Asegura que el servicio de la base de datos esté listo antes de iniciar la app
    command: ["./wait-for-it.sh", "db:5432", "--", "npm", "start"]
  db:
    image: postgres:14 # Usa la imagen oficial de PostgreSQL
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1986
      POSTGRES_DB: inyectoras_db
    ports:
      - "5433:5432" # Mapea el puerto 5432 del contenedor al puerto 5432 de tu máquina
    volumes:
      - db_data:/var/lib/postgresql/data # Persiste los datos de la base de datos

volumes:
  db_data: